export const INITIALIZE_RESTAURANT_TABLE_IDS = 'INITIALIZE_RESTAURANT_TABLE_IDS';

export const REQUEST_START = 'REQUEST_START';
export const FETCH_FOOD_SUCCESS = 'FETCH_FOOD_SUCCESS';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';

export const GET_ORDERS_STATUS = 'GET_ORDERS_STATUS';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const UPDATE_CART_ITEMS = 'UPDATE_CART_ITEMS';
export const REMOVE_ITEMS = 'REMOVE_ITEMS';

export const REMOVE_ALL_ORDERS = 'REMOVE_ALL_ORDERS';
export const DELETE_ORDER = 'DELETE_ORDER';

export const RESET_DATA = 'RESET_DATA';

