export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_TABLES = 'FETCH_TABLES';
export const FETCH_ADDITIONS = 'FETCH_ADDITIONS';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_FOODS = 'FETCH_FOODS';
export const FETCH_DELIVERIES = 'FETCH_DELIVERIES';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_TABLE = 'CREATE_TABLE';
export const CREATE_ADDITION = 'CREATE_ADDITION';
export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';
export const CREATE_FOOD = 'CREATE_FOOD';
export const CREATE_DELIVERY = 'CREATE_DELIVERY';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_TABLE = 'UPDATE_TABLE';
export const UPDATE_ADDITION = 'UPDATE_ADDITION';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const UPDATE_FOOD = 'UPDATE_FOOD';
export const UPDATE_DELIVERY = 'UPDATE_DELIVERY';

export const RETRIEVE_USER = 'RETRIEVE_USER';
export const RETRIEVE_CATEGORY = 'RETRIEVE_CATEGORY';
export const RETRIEVE_ORDER = 'RETRIEVE_ORDER';
export const RETRIEVE_TABLE = 'RETRIEVE_TABLE';
export const RETRIEVE_ADDITION = 'RETRIEVE_ADDITION';
export const RETRIEVE_RESTAURANT = 'RETRIEVE_RESTAURANT';
export const RETRIEVE_FOOD = 'RETRIEVE_FOOD';
export const RETRIEVE_DELIVERY =  'RETRIEVE_DELIVERY';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_TABLE = 'DELETE_TABLE';
export const DELETE_ADDITION = 'DELETE_ADDITION';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const DELETE_FOOD = 'DELETE_FOOD';
export const DELETE_DELIVERY = 'DELETE_DELIVERY';

export const PROCESSING_REQUEST = 'PROCESSING_REQUEST';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_SUCCEED = 'REQUEST_SUCCEED';

export const NOTIFY_USER = 'NOTIFY_USER';