export const INITIALIZE_RESTAURANT_TABLE_IDS = 'INITIALIZE_RESTAURANT_TABLE_IDS';

export const REQUEST_START = 'REQUEST_START';
export const FETCH_FOOD_SUCCESS = 'FETCH_FOOD_SUCCESS';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';

export const GET_ORDERS_STATUS = 'GET_ORDERS_STATUS';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const UPDATE_CART_ITEMS = 'UPDATE_CART_ITEMS';
export const REMOVE_ITEMS = 'REMOVE_ITEMS';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';

export const REMOVE_ALL_ORDERS = 'REMOVE_ALL_ORDERS';
export const DELETE_ORDER = 'DELETE_ORDER';

export const RESET_DATA = 'RESET_DATA';

export const CHANGE_INPUT = 'CHANGE_INPUT';


export const ASK_ADDITION = 'ASK_ADDITION';


export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_TABLES = 'FETCH_TABLES';
export const FETCH_ADDITIONS = 'FETCH_ADDITIONS';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_FOODS = 'FETCH_FOODS';

export const ADD_USERS = 'ADD_USERS';
export const SET_ORDER_TYPE = 'SET_ORDER_TYPE';