# Generated by Django 3.0.1 on 2020-01-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxureally_api', '0002_auto_20191227_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/pictures/'),
        ),
    ]
