# Generated by Django 3.0.1 on 2020-01-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxureally_api', '0003_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('status', models.CharField(choices=[('PENDING ORDER', 'PENDING ORDER'), ('ORDER TREATED', 'ORDER TREATED'), ('ORDER DELIVERED', 'ORDER DELIVERED')], default='PENDING ORDER', max_length=50)),
                ('order_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
