# Generated by Django 3.0.1 on 2020-01-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxureally_api', '0005_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='status',
            field=models.CharField(choices=[('NON PAID', 'NON PAID'), ('PAID', 'PAID')], default='NON PAID', max_length=20),
        ),
    ]
