# Generated by Django 3.0.1 on 2020-01-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luxureally_api', '0006_addition_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='order_details',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='luxureally_api.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='on-place', max_length=50),
        ),
    ]
