# Generated by Django 3.0.1 on 2020-01-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxureally_api', '0008_auto_20200106_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING ORDER', 'Commande en cours'), ('ORDER TREATED', 'Votre commande est prête'), ('ORDER DELIVERED', 'Commande livrée')], default='PENDING ORDER', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING ORDER', 'Commande en cours'), ('ORDER TREATED', 'Votre commande est prête'), ('ORDER DELIVERED', 'Commande livrée')], default='PENDING ORDER', max_length=50),
        ),
    ]
