# Generated by Django 3.0.1 on 2020-01-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxureally_api', '0009_auto_20200108_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('COMMANDE EN COURS', 'Commande en cours'), ('COMMANDE PRETE', 'Votre commande est prête'), ('COMMANDE LIVREE', 'Commande livrée')], default='COMMANDE EN COURS', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('COMMANDE EN COURS', 'Commande en cours'), ('COMMANDE PRETE', 'Votre commande est prête'), ('COMMANDE LIVREE', 'Commande livrée')], default='COMMANDE EN COURS', max_length=50),
        ),
    ]
